name: Dependency Caching Demo
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Caching Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm 
          key: node-modules-${{ hashFiles('**/packages-lock.json') }}
      - name: Install Dependencies
        run: npm ci