name: Matrix Demo
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        OPERATING_SYSTEM: [ubuntu-latest, windows-latest, macos-latest]
        NODE_VERSION: [12,14,15,17,18]
    runs-on: ${{ matrix.OPERATING_SYSTEM }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NODE_VERSION }}