name: Output
on:
 push:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      file-name: ${{ steps.file.outputs.output-value }}
    steps:
      - name: Output Something
        id: file
        run: echo 'output-value=someSecret' >> $GITHUB_OUTPUT
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Output Value
        run: echo "${{ needs.build.outputs.file-name }}"
